### ISSUE TITLE
Component not working on Firefox

### ISSUE THREAD

**Issue by alanlimateles** [enreeco/inputlookup#1]
The component works fine on Chrome, but in firefox, when I press tab on first field or fucus in other, the first one erases

**Comment by enreeco** [comment]
Thanks for the issue.
I'm developing a quick fix.

**Comment by enreeco** [comment]
It was a problema related to the "onchange" event on the input textbox. I've refactored the onchange handler to be a "onkeyup" handler directly with jQuery

**Comment by enreeco** [comment]
Commit Issue #1

**Comment by alanlimateles** [comment]
Tnx!
