### ISSUE TITLE
Input field is not coming, when locker service is enabled.

### ISSUE THREAD

**Issue by rajendrasnagar** [enreeco/inputlookup#2]
Hello Enrico, 

Thanks for sharing this.

I was trying to look into this, but for me its not working:
Steps:
1. I created all the components, events, static resources as mentioned. And, yes it is working in Salesforce Classic.
2. However, When I turn on Lightning service. I can't see input field (cf: attached snapshot).
![image](https://cloud.githubusercontent.com/assets/3901703/17303080/bde0b48a-583c-11e6-8331-e882e95941fc.png)

Can you help in resolving this issue.

Thanks in Advance.

Regards,
Raj

**Comment by raJSN** [comment]
![image](https://cloud.githubusercontent.com/assets/3901703/17303276/966267ae-583d-11e6-9511-a7c56af6930d.png)
More Analysis from my side.

**Comment by rajendrasnagar** [comment]
![image](https://cloud.githubusercontent.com/assets/3901703/17303293/af9618a6-583d-11e6-96f9-929354dedf03.png)

More Analysis from my side.

**Comment by enreeco** [comment]
I'll get an eye soon, thanks for the feedbacks

**Comment by enreeco** [comment]
Which browser are you using?

**Comment by enreeco** [comment]
I have installed the following package (that contains the whole components) and I got it working on another dev org: https://login.salesforce.com/packaging/installPackage.apexp?p0=04t24000000TxtD
You have the error I had before updating the code.
Maybe it's a matter of browser, which one are you using?

**Comment by rajendrasnagar** [comment]
I am Using Chrome Latest version. 
Meanwhile, I will try to install the pckg you mentioned & check once again.
Thanks

**Comment by rajendrasnagar** [comment]
Hi Enrico,

Thanks for your help. I replaced all the compnents with the one you passed and it is working now. There seems to be issue with Chrome Cache.

Thanks Again.

Regards,
Raj

**Comment by kevindeslauriers** [comment]
raJSN how did you rectify? I get the same issue on my test org where I need to use a lookup but when I install to a different org I don't.

**Comment by rajendrasnagar** [comment]
@kevindeslauriers , Yes I was also facing this issue in similar way. However, as I was in hurry, I didn't concentrate on root case. 
To fix this, I just replaced all the entities of non-working components with entities of  working components. And, It started working. 
I will say to replace static resource file & delete all cache from chrome. Or best, test in other browser.
Best of Luck...

**Comment by kevindeslauriers** [comment]
@raJSN thanks - I had replaced the resources but had not cleared the cache.  That did the trick.  Have you been able to get it to work in SF1?

**Comment by rajendrasnagar** [comment]
Hi @kevindeslauriers , No dude... not tested in SF1 app....
