### ISSUE TITLE
It is not working with SLDS

### ISSUE THREAD

**Issue by rajendrasnagar** [enreeco/inputlookup#3]
Hi Enreeco,

Thanks for sharing your solution. This is build on top of Twitter bootstrap.

However, if we use it along with SLDS it breaks css on lot of places. Note, We have used scoped version of SLDS, but still we are facing the error.

Can you help to resolve these issues.

Regards,
Raj

**Comment by enreeco** [comment]
Have you tried replacing bootstrap css with a scoped one? you have to replace the component's bootstrap.css with a namespaced one (e.g. usigin this awesome tool http://www.css-prefix.com/) and add a class on top of the inputLookup element. I may try to have a look at it but I don't know when!

**Comment by rajendrasnagar** [comment]
Thanks enreeco for you feedback, will check this out.

**Comment by rajendrasnagar** [comment]
Yo, its working with Scoped Bootstrap.
Thanks again :+1:
