### ISSUE TITLE
Component not working in Safari.

### ISSUE THREAD

**Issue by JaroslawKolodziejczykClorce** [enreeco/inputlookup#7]
Hi,

Thanks for sharing such an awesome component, it's working great in Chrome, but when i try to use it in Safari clicking on it just makes it greyed out and nothing happens.

I'm also using it in communities and it works in chrome but again is not working in Safari.

Locker Service is Enabled.

**Comment by enreeco** [comment]
Thanks @JaroslawKolodziejczykClorce , I'll check

**Comment by enreeco** [comment]
Hi @JaroslawKolodziejczykClorce ,
Can you please retry with the last code just pushed?

**Comment by JaroslawKolodziejczykClorce** [comment]
I just checked and now it's working, we found a decent workaround but this will surely be useful in future :) thanks 👍

**Comment by JaroslawKolodziejczykClorce** [comment]
Oh damn, it's working even without the new code(i just checked without changing it to new issue), i guess new Summer 17 release has something to do with this (my org instance is on preview sandbox version)?

I can't test this right now on old api version but i'll try if i find time for it (with new issue code).
